# I went through Mike Cohen's deep learning course - my code has more comments and added goodies (modified from the original) and will walk you through it -- or you can sign up here:
https://www.udemy.com/course/deeplearning_x/learn/lecture/27841856#overview

# Using NumPy

In [ ]:
# 1st STEP ** Always remember to import the required libraries.
import numpy as np
import torch

In [ ]:
# Let's understand a vector - a number with direction, a one dimensional row or column

In [24]:
# Let's create a new vector
newVector = np.array([ [1,2,3,4] ]) # we name our variable and call NumPy as np
print(newVector), print(' ')

# let's transpose the vector to a column
print(newVector.T), print(' ') # this just prints, not permanent change

# and back again to a row
newVectorT = newVector.T
print(newVectorT.T) # below we can watch the transposition from row, column, row :-)
# let's check datatype and our dimensionality
nvDtype = newVector.dtype
print(nvDtype) # numpy sees these as n dimensiol arrays, aka, NDARRAYS - 64bit integer

newVector.ndim # 2 dimensions is the result

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]
int64


2

In [17]:
# Now we can move on to a matrix or an n dimensional array, similar to a spreadsheet
# n number of rows and columns

newMatrix = np.array([ [1,2,3,4],
                       [6,7,8,9]
                       ])
print(newMatrix), print(' ')

print(newMatrix.T), print(' ') # this just prints, not permanent change, notice the 1st
# row becomes the 1st column, 2nd - 2nd, 3rd - 3rd etc. to however many n columns

newMatrixT = newMatrix.T
print(newMatrixT.T) # same as above, takes it back to its original state
newMatrix.ndim # we can see that it is a 2 dimension shape - 2 is the result below

[[1 2 3 4]
 [6 7 8 9]]
 
[[1 6]
 [2 7]
 [3 8]
 [4 9]]
 
[[1 2 3 4]
 [6 7 8 9]]


2

# Now let's do the same, but let's use PyTorch!

In [25]:
torchVector = torch.tensor([ [1,2,3,4] ]) # understand that pytorch defines
# scalars, vectors, matrices, and tensors, you guessed it... as tensors.
print(torchVector), print(' ')

print(torchVector.T) , print(' ')

torchVectorT = torchVector.T
print(torchVectorT.T)

tvDtype = torchVector.dtype # let's check our datatype and dimesnionality
print(tvDtype) # datatype is a torch tensor - 64bit integer

torchVector.ndim

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])
torch.int64


2

In [33]:
# let's do a matrix with torch
torchMatrix = torch.tensor([ [1,2,3,4,],
                            [6,7,8,9,]
                             ])
print(torchMatrix), print(' ')

print(torchMatrix.T), print(' ')

torchMatrixT = torchMatrix.T
print(torchMatrixT.T)

tmDtype = torchMatrix.dtype
print(tmDtype)
torchMatrix.ndim

tensor([[1, 2, 3, 4],
        [6, 7, 8, 9]])
 
tensor([[1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])
 
tensor([[1, 2, 3, 4],
        [6, 7, 8, 9]])
torch.int64


2

In [36]:
# for a more a more robust and in depth return of dtypes, try this :-)
print(f'Variable newVector is of dtype {type(newVector)}')
print(f'Variable newMatrix is of dtype {type(newMatrix)}')
print(f'Variable torchVector is of dtype {type(torchVector)}')
print(f'Variable torchMatrix is of dtype {type(torchMatrix)}')

Variable newVector is of dtype <class 'numpy.ndarray'>
Variable newMatrix is of dtype <class 'numpy.ndarray'>
Variable torchVector is of dtype <class 'torch.Tensor'>
Variable torchMatrix is of dtype <class 'torch.Tensor'>
