<a href="https://colab.research.google.com/github/flowmasterB/learningPyTorch/blob/main/00_pytorch_math_matrix_multiply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# I went through Mike Cohen's deep learning course (modified from the original - I add more comments and code where I see fit to further solidify concepts) and will walk you through it -- or you can sign up here:
https://www.udemy.com/course/deeplearning_x/learn/lecture/27841856#overview

In [2]:
# import libraries
import numpy as np
import torch

# Using NumPy

In [23]:
# create random matrices -- note** a capital letter indicates a matrix
A = np.random.randn(3,4) # creates random matrix 3 rows 4 cols
B = np.random.randn(4,5) # creates random matrix 4 rows 5 cols
C = np.random.randn(3,7) # creates random matrix 3 rows 7 cols

print(A), print(' ') # I add a line to separate them for easier viewing
print(B), print(' ')
print(C)

# for the following examples -- uncomment then comment the line back
np.matmul(A,B) # python multiply
A@C# shortcut for multiply
# check with C - rotate the sequence and see if they will multiply -
# matrices multiply the outer only if the inners are congruent
# i.e. m1 [1,2] m2 [3,2] wil not  work, whereas [1,2] [2,3] would - 2 2 inner


[[-0.33113844  0.1826392  -2.06198769  2.60472962]
 [-0.85332969 -1.73008821  0.40115948  0.23957054]
 [-1.36432831  0.46223122 -0.3722126   1.00807397]]
 
[[ 1.3724463   0.59855468 -0.10646262 -0.32034025 -0.19775052]
 [-1.06668127  1.90471004  1.54042228  0.4809631  -1.16533517]
 [ 0.02000058 -1.13586999 -0.35217225  0.43461363 -0.32164794]
 [-1.12478947 -1.08044313  1.12179673  0.06874414  1.43926075]]
 
[[ 0.77048948  1.63433634  0.18236107 -1.88388415 -0.84227712 -0.87074238
  -0.44624197]
 [-2.06731164  0.14532464 -0.61803738 -2.01175788 -0.50384037 -0.15520821
  -0.39007199]
 [ 2.05663208 -0.55504993 -1.31078196 -1.14231016  0.16420996  1.17232545
  -0.578566  ]]


ValueError: ignored

In [26]:
# See, we were returned an error, because the inner values were not congruent
# Let's try A@B
A@B # We are returned new NDARRAY from NumPy
print({type(A@B)})

{<class 'numpy.ndarray'>}


In [31]:
A@B # We have a very precise floated array
# Let's try to shorten these up
print(A@B), print(' ')
print(np.round(A@B   ,2)), print(' ')

[[-3.62030097 -0.32244203  3.96474737 -0.52318837  4.26476611]
 [ 0.41286052 -4.52058823 -2.44674649 -0.36793429  2.40065137]
 [-3.50683617 -0.60259013  2.11921826  0.56689595  1.30174505]]
 
[[-3.62 -0.32  3.96 -0.52  4.26]
 [ 0.41 -4.52 -2.45 -0.37  2.4 ]
 [-3.51 -0.6   2.12  0.57  1.3 ]]
 


(None, None)

In [35]:
# NICE! Easier on the eyes yeah? :-)

In [36]:
# Let's do a transpose -- but A and C won't multiply! -- TRANSPOSE!
print(np.round( C.T@A,   2)) # C is 3,7 - transpose 7,3 and multiply by A 3,4

[[-1.3   4.67 -3.18  3.58]
 [ 0.09 -0.21 -3.11  3.73]
 [ 2.26  0.5  -0.14 -0.99]
 [ 3.9   2.61  3.5  -6.54]
 [ 0.48  0.79  1.47 -2.15]
 [-1.18  0.65  1.3  -1.12]
 [ 1.27  0.33  0.98 -1.84]]


# Using PyTorch

In [45]:
# create random matrices -- note** a capital letter indicates a matrix
At = torch.randn(3,4) # creates random matrix 3 rows 4 cols
Bt = torch.randn(4,5) # creates random matrix 4 rows 5 cols
Ct = np.random.randn(4,7) # creates random matrix 4 rows 7 cols - a np array!
Ct2 = torch.tensor( Ct,dtype=torch.float ) # We convert NDARRAY to a tensor
print(At), print(' ') # I add a line to separate them for easier viewing
print(Bt), print(' ')
print(Ct), print(' ')
print(Ct2)

# can we multiply a np array and a torch tensor?

print(np.round( A@Ct2  ,2))

tensor([[ 0.2248,  0.4896,  0.4200, -0.5701],
        [ 1.0696,  0.8745,  1.8540, -0.6219],
        [ 0.0565, -0.3721,  0.5928, -1.4072]])
 
tensor([[ 0.1093,  1.8499, -0.7677, -0.2567,  1.0002],
        [-0.3612,  0.9117,  0.1066,  1.7451,  1.1985],
        [ 0.4639, -1.6284,  1.9700,  0.0604, -0.0561],
        [-1.1660,  1.3610,  1.0319, -1.1278, -1.6011]])
 
[[ 0.7382894  -0.08035364 -0.57938427  0.53964095 -1.05570451  0.37549975
  -0.71727673]
 [ 0.2983628  -0.17238746  0.09099311 -0.2581923   1.58425867  0.80005948
  -1.6777531 ]
 [-0.43672344 -0.10841492 -1.38851007 -0.94035695 -0.1712289   1.48218764
  -0.48945847]
 [ 1.76260256  1.84695337 -1.37457305  0.1390787   0.94840486  1.63178782
   0.66992666]]
 
tensor([[ 0.7383, -0.0804, -0.5794,  0.5396, -1.0557,  0.3755, -0.7173],
        [ 0.2984, -0.1724,  0.0910, -0.2582,  1.5843,  0.8001, -1.6778],
        [-0.4367, -0.1084, -1.3885, -0.9404, -0.1712,  1.4822, -0.4895],
        [ 1.7626,  1.8470, -1.3746,  0.1391,  0.9484,  1.6

TypeError: ignored

In [47]:
# NOPE
# let's try
At@Bt

tensor([[ 0.7073, -0.5976,  0.1187,  1.4650,  1.7009],
        [ 1.3862, -1.0895,  2.2826,  2.0650,  3.0097],
        [ 2.0563, -3.1152, -0.3673,  0.9588,  1.8303]])

In [50]:
# YEP
Bt@Ct

ValueError: ignored

In [52]:
# NOPE
At@Ct

tensor([[-0.8762, -1.2009,  0.1147, -0.4793, -0.0743,  0.1684, -1.5701],
        [-0.8553, -1.5863, -2.2596, -1.4785, -0.6511,  2.8344, -3.5585],
        [-2.8085, -2.6036,  1.0446, -0.6266, -2.0853, -1.6942, -0.6490]],
       dtype=torch.float64)

In [54]:
# YEP
At@Bt.T

RuntimeError: ignored

In [56]:
# NOPE
Bt.T@Ct # there we go a transpose and now Bt and Ct can multiply!

tensor([[-2.2849, -2.1504,  0.8625, -0.4461, -1.8728, -1.4630, -0.4806],
        [ 4.7478,  2.3844, -0.5986,  2.4834,  1.0610,  1.2313, -1.1476],
        [ 0.4235,  1.7356, -3.6992, -2.1507,  1.6206,  4.4007,  0.0989],
        [-1.6830, -2.3697,  1.7738, -0.8028,  1.9558, -0.4509, -3.5289],
        [-1.7016, -3.2381,  1.8083,  0.0604, -0.6661, -1.3614, -3.7734]],
       dtype=torch.float64)

In [59]:
# Let's try Ct2
At@Ct2 # BTW you can use the numpy round print(np.round(At@Ct2,  2)) also ;-)

tensor([[-0.8762, -1.2009,  0.1147, -0.4793, -0.0743,  0.1684, -1.5701],
        [-0.8553, -1.5863, -2.2596, -1.4785, -0.6511,  2.8344, -3.5585],
        [-2.8085, -2.6036,  1.0446, -0.6266, -2.0853, -1.6942, -0.6490]])

In [61]:
# YEP
Bt@Ct2

RuntimeError: ignored

In [62]:
# NOPE -- let's transpose!
Bt.T@Ct2 # YEP!!!! Wooo Hoooo!

tensor([[-2.2849, -2.1504,  0.8625, -0.4461, -1.8728, -1.4630, -0.4806],
        [ 4.7478,  2.3844, -0.5986,  2.4834,  1.0610,  1.2313, -1.1476],
        [ 0.4235,  1.7356, -3.6992, -2.1507,  1.6206,  4.4007,  0.0989],
        [-1.6830, -2.3697,  1.7738, -0.8028,  1.9558, -0.4509, -3.5289],
        [-1.7016, -3.2381,  1.8083,  0.0604, -0.6661, -1.3614, -3.7734]])